#!/usr/bin/env python3
"""Generate a deterministic synthetic FIF and public Pages demonstration."""

from pathlib import Path
import sys

import mne
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from eeg_tfr_volume import BuildConfig, compute_tfr_volume, write_viewer  # noqa: E402


def main() -> None:
    data_dir = ROOT / "data"
    data_dir.mkdir(exist_ok=True)
    fif = data_dir / "synthetic_demo_raw.fif"
    sfreq = 200.0
    channels = ["O1", "Oz", "O2", "P3", "Pz", "P4", "C3", "Cz", "C4", "F3", "Fz", "F4"]
    info = mne.create_info(channels, sfreq, ch_types="eeg")
    info.set_montage("standard_1020")
    duration = 34.0
    times = np.arange(round(duration * sfreq)) / sfreq
    rng = np.random.default_rng(20261003)
    data = rng.normal(0, 2.0e-6, (len(channels), len(times)))
    onsets = np.arange(2.0, 31.0, 4.0)
    for onset in onsets:
        envelope = np.exp(-0.5 * ((times - (onset + 0.65)) / 0.20) ** 2)
        spatial = np.linspace(0.5, 1.25, len(channels))[:, None]
        data += spatial * 4.5e-6 * np.sin(2 * np.pi * 12 * times)[None, :] * envelope
    raw = mne.io.RawArray(data, info, verbose="ERROR")
    raw.set_annotations(mne.Annotations(onsets, np.zeros(len(onsets)), ["demo"] * len(onsets)))
    raw.save(fif, overwrite=True, verbose="ERROR")

    config = BuildConfig(
        input=str(fif), event="demo", tmin=-0.4, tmax=2.0,
        fmin=4.0, fmax=40.0, n_freqs=24, cycles=3.0,
        time_step=0.025, epoch_batch_size=4,
    )
    volume, epoch_times, freqs, ordered_channels, metadata = compute_tfr_volume(config)
    metadata["input"] = {
        "description": "Deterministic synthetic EEG generated by scripts/generate_demo.py"
    }
    metadata["config"]["input"] = "data/synthetic_demo_raw.fif"
    write_viewer(ROOT / "docs" / "index.html", volume, epoch_times, freqs, ordered_channels, metadata)
    print(ROOT / "docs" / "index.html")


if __name__ == "__main__":
    main()
